<?php echo $this->menu; ?>

<div class="merchant_contentbox">

    <?php if (count($this->paginator)): ?>
    
    <?php echo $this->paginationControl($this->paginator,
                                        'Sliding',
                                        'widget/pagination-control', array('route' => 'merchant/trade_paginator')); ?>
    
    <table class="table table-hover">
        <thead>
            <tr>
                <th>编号</th>
                <th>商家订单号</th>
                <th>支付接口类型</th>
                <th>支付交易号</th>
                <th>金额</th>
                <th>创建时间</th>
                <th>支付时间</th>
                <th>支付状态</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->paginator as $item): ?>
              <tr>
                <td><?php echo $item['id']; ?></td>
                <td><?php echo $item['merchant_trade_id']; ?></td>
                <td><?php echo $item['payment_interface_type']; ?></td>
                <td><?php if ($item['payment_interface_trade_id']) echo $item['payment_interface_trade_id'];else echo 'N/A'; ?></td>
                <td><?php echo $item['price']; ?></td>
                <td><?php echo $item['create_time']; ?></td>
                <td><?php if ($item['pay_time']) echo $item['pay_time'];else echo 'N/A'; ?></td>
                <td><?php if ($item['pay_status']) echo '<span style="color:green;">已支付</span>'; else echo '<span style="color:red;">未支付</span>'; ?></td>
              </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    
    <?php echo $this->paginationControl($this->paginator,
                                        'Sliding',
                                        'widget/pagination-control', array('route' => 'merchant/trade_paginator')); ?>
    
    <?php endif; ?>

</div>