<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Setting\Module'                        => __DIR__ . '/Module.php',
    'Setting\Controller\PaymentController' => __DIR__ . '/src/Setting/Controller/PaymentController.php',
    'SettingTest\Framework\TestCase'        => __DIR__ . '/tests/Setting/Framework/TestCase.php',
    'SettingTest\SampleTest'                => __DIR__ . '/tests/Setting/SampleTest.php',
);
