<p class="alert alert-success" style="padding: 20px; font-size: large;">
    <span class="glyphicon glyphicon-yen" aria-hidden="true"></span>
    <?php echo sprintf($this->translate('You are going to pay %s to the merchant.'),$this->currencyFormat($this->price,'RMB', null, 'zh_cn')); ?>
</p>


<h3><?php echo $this->translate('Please select the payment method:');?></h3>


<div style="padding: 20px;">
    <label><input type="radio" name="payment_method" value="alipay"<?php 
    if (empty($this->selected_payment) || $this->selected_payment == 'alipay'){
        echo ' checked';
    }
    ?>>&nbsp;&nbsp;<img src="/img/alipay.png" alt="<?php echo $this->translate('Alipay');?>"></label><br>
    
    <label><input type="radio" disabled name="payment_method" value="wechatpay"<?php 
    if ($this->selected_payment == 'wxpay'){
        echo ' checked';
    }
    ?>>&nbsp;&nbsp;<img src="/img/wechatpay.png" alt="<?php echo $this->translate('Wechatpay');?>">(<?php echo $this->translate('Comming soon !');?>)</label><br>
    
</div>

<input class="form-control btn btn-primary" type="button" id="pay_btn" value="<?php echo $this->translate('Pay Now !');?>">


<script type="text/javascript">
$(document).ready(function($){
	$("#pay_btn").click(function(){

		this.value = 'Please wait ...';
		$(this).attr('disabled','true');

		var payment_method = $('input:radio[name=payment_method]:checked').val();

		<?php /* Save the payment_method to DB & Redirect to the selected PayInterface gateway if Save the payment_method successlly.  */ ?>

		$.ajax({
			   type: "POST",
			   dataType:"json",
			   url: "<?php echo $this->url('cashier/setpayment') ?>",
			   data: {merchant:"<?php echo $this->merchant; ?>",trade:"<?php echo $this->trade; ?>",payment_method:payment_method},
			   success:function(data){
					console.log(data);

					// Redirect to the selected PayInterface gateway.
					if (data.status == 'true'){
						var href_tpl = '<?php echo $this->url('cashier/gateway',array('action'=>'gate_type')) ?>';
						var href = href_tpl.replace('gate_type',data.interface);
						location.href = href;
					}
					
				},
				error:function(XMLHttpRequest, textStatus, errorThrown){
					console.log(XMLHttpRequest, textStatus, errorThrown);
				}
			});
		
	});
});
</script>
