<p>You are going to pay ￥<span><?php echo $this->price; ?></span> to the merchant.</p>


<h4>Please select the payment method:</h4>



<p><label><input type="radio" name="payment_method" value="alipay"<?php 
if (empty($this->selected_payment) || $this->selected_payment == 'alipay'){
    echo ' checked';
}
?>>Alipay(Suport BandCard Payment.)</label></p>
<p><label><input type="radio" name="payment_method" value="wechatpay"<?php 
if ($this->selected_payment == 'wxpay'){
    echo ' checked';
}
?>>Wechatpay</label></p>


<p><input type="button" id="pay_btn" value="Pay Now !"></p>


<script type="text/javascript">
$(document).ready(function($){
	$("#pay_btn").click(function(){

		this.value = 'Please wait ...';
		$(this).attr('disabled','true');

		var payment_method = $('input:radio[name=payment_method]:checked').val();

		<?php /* Save the payment_method to DB & Redirect to the selected PayInterface gateway if Save the payment_method successlly.  */ ?>

		$.ajax({
			   type: "POST",
			   dataType:"json",
			   url: "<?php echo $this->url('cashier/setpayment') ?>",
			   data: {merchant:"<?php echo $this->merchant; ?>",trade:"<?php echo $this->trade; ?>",payment_method:payment_method},
			   success:function(data){
					console.log(data);

					// Redirect to the selected PayInterface gateway.
					if (data.status == 'true'){
						var href_tpl = '<?php echo $this->url('cashier/gateway',array('action'=>'gate_type')) ?>';
						var href = href_tpl.replace('gate_type',data.interface);
						location.href = href;
					}
					
				},
				error:function(XMLHttpRequest, textStatus, errorThrown){
					console.log(XMLHttpRequest, textStatus, errorThrown);
				}
			});
		
	});
});
</script>
