
<?php echo $this->menu; ?>

<div class="merchant_contentbox">


<?php $this->placeholder('test')->set('sdfsdfsd'); ?>

<h4><?php echo $this->translate('Welcome to Easypay Merchant Center !'); ?></h4>

<p><?php echo $this->translate('Totle Income:'); ?> 4545.50</p>
<p><?php echo $this->translate('Free Income:'); ?> 3545.50</p>
<p><?php echo $this->translate('Withdrawed Income:'); ?> 2000.00</p>
<p><?php echo $this->translate('Effective Income:'); ?> 1545.50</p>
<p><?php echo $this->translate('Trade:'); ?> 34/50</p>
<p><?php echo $this->translate('Withdraw Request:'); ?> 5/6</p>

</div>