<?php
$active = function( $test_RouteName ){
    if ($test_RouteName ==  $this->RouteName) echo ' class="active"';
} 
?>
<ul class="nav nav-tabs">
  <li role="presentation"<?php $active('merchant'); ?>><a href="<?php echo $this->url('merchant') ?>">总览</a></li>
  <li role="presentation"<?php $active('merchant/setting'); ?>><a href="<?php echo $this->url('merchant/setting') ?>">提现方式设置</a></li>
  <li role="presentation"<?php $active('merchant/withdraw'); ?>><a href="<?php echo $this->url('merchant/withdraw',array('action'=>'add')) ?>">我要提现</a></li>
  <li role="presentation"<?php $active('merchant/withdraw_paginator'); ?>><a href="<?php echo $this->url('merchant/withdraw_paginator') ?>">提现单查阅</a></li>
  <li role="presentation"<?php $active('merchant/trade_paginator'); ?>><a href="<?php echo $this->url('merchant/trade_paginator') ?>">交易单查阅</a></li>
</ul>