<?php echo $this->menu; ?>

<div class="merchant_contentbox">

    <h3 class="text-center"><?php echo $this->translate('Make an Withdraw.');?></h3>
    
    <?php
    $form = $this->form;
    $form->get('withdraw_type')->setLabel($this->translate('Withdraw Method'));
    $withdraw_type_ValueOption = $form->get('withdraw_type')->getValueOptions();
    $withdraw_type_ValueOption[\Merchant\Model\Withdraw::WITHDRAW_TYPE_ALIPAY] = $this->translate('Alipay');
    $withdraw_type_ValueOption[\Merchant\Model\Withdraw::WITHDRAW_TYPE_BANK] = $this->translate('BankCard');
    $form->get('withdraw_type')->setValueOptions($withdraw_type_ValueOption);
    $form->get('price')->setLabel($this->translate('Amount'))->setAttributes(array(
        'min'  => '100',
        'max'  => $form->get('price')->getValue(),
    ));
    $form->get('submit')->setAttributes(array(
        'value' => $this->translate('Submit'),
        'id' => 'submitbutton',
    ));
    $form->prepare();
    ?>

    
    <P class="bg-warning text-center" style="padding: 20px; font-size:medium;"><span class="glyphicon glyphicon-alert" aria-hidden="true" style="color: Orange; font-size: xx-large;"></span> <?php echo $this->translate('You can withdraw at most');?> <span style="font-weight: bold; font-style: italic;"><?php echo $this->currencyFormat($report->EnableMakeWithdraw,'RMB', null, 'zh_cn'); ?></span></P>
    
    <?php
    if ($this->is_post):
        if ($this->status):
    ?>
            <p class="bg-success text-center" style="padding: 10px; font-size:medium;"> <span class="glyphicon glyphicon-ok" aria-hidden="true" style="color: Green; font-size: xx-large;"></span><br><?php echo sprintf($this->translate('You had submit a withdraw request successfully for %s ,<br>please wait till the customer service staff proccessed it,<br>you can also check the progress status in %s Withdraw Request List %s'),$this->currencyFormat($form->get('price')->getValue(),'RMB', null, 'zh_cn'),'<a href="'.$this->url('merchant/withdraw_paginator').'">','</a>');?></p>
    
    <?php 
        else:
    ?>
            <p class="bg-success text-center" style="padding: 10px; font-size:medium;"> <span class="glyphicon glyphicon-remove" aria-hidden="true" style="color: Red; font-size: xx-large;"></span><br><?php echo $this->translate('System Error !<br> Your Submited had failed !'); ?></p>
    <?php 
        endif;
    endif;
    ?>
    
    
    <?php
    echo $this->form()->openTag($form->setAttribute('class','form-horizontal'));
    ?>
    
    <div class="form-group">
        <?php echo $this->formlabel($form->get('withdraw_type')->setLabelAttributes(array('class' => 'col-sm-3 col-lg-2 control-label'))) ?>
        <div class="col-sm-9 col-lg-10">
            <?php echo $this->formselect($form->get('withdraw_type')->setAttribute('class','form-control')); ?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formlabel($form->get('price')->setLabelAttributes(array('class' => 'col-sm-3 col-lg-2 control-label'))) ?>
        <div class="col-sm-9 col-lg-10">
            <?php echo $this->formnumber($form->get('price')->setAttribute('class','form-control')); ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9 col-lg-offset-2 col-lg-10">
        <?php echo $this->formSubmit($form->get('submit')->setAttributes(array(
            'class' => 'form-control btn btn-default'
        ))); ?>
        </div>
    </div>
    
    <?php echo $this->form()->closeTag(); ?>

</div>