<?php echo $this->menu; ?>


<div class="merchant_contentbox">

    <h3 class="text-center"><?php echo $this->translate('Setting up the merchant info.');?></h3>
    <?php
    $form = $this->form;
    $form->get('alipay_account')->setLabel($this->translate('Alipay Account'));
    $form->get('bank_type')->setLabel($this->translate('Bank Name'));
    $form->get('bank_account_name')->setLabel($this->translate('Bank Account Name'));
    $form->get('bank_account_card')->setLabel($this->translate('Bank Account Card'));
    $form->get('submit')->setAttributes(array(
        'value' => $this->translate('Save'),
        'id' => 'submitbutton',
    ));
    $form->prepare();
    ?>
    
    
    <?php
    if ($this->is_post):
        if ($this->status):
    ?>
            <p class="bg-success text-center" style="padding: 10px; font-size:medium;"> <span class="glyphicon glyphicon-ok" aria-hidden="true" style="color: Green; font-size: xx-large;"></span><br><?php echo $this->translate('Configuration save successfully !');?></p>
    
    <?php 
        else:
    ?>
            <p class="bg-success text-center" style="padding: 10px; font-size:medium;"> <span class="glyphicon glyphicon-remove" aria-hidden="true" style="color: Red; font-size: xx-large;"></span><br><?php echo $this->translate('System Error !<br> Configuration saved had failed !'); ?></p>
    <?php 
        endif;
    endif;
    ?>
    
    
    <?php
    echo $this->form()->openTag($form->setAttribute('class','form-horizontal'));
    ?>
    
    <div class="form-group">
        <?php echo $this->formlabel($form->get('alipay_account')->setLabelAttributes(array('class' => 'col-sm-3 col-lg-2 control-label'))) ?>
        <div class="col-sm-9 col-lg-10">
            <?php echo $this->formText($form->get('alipay_account')->setAttribute('class','form-control')); ?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formlabel($form->get('bank_type')->setLabelAttributes(array('class' => 'col-sm-3 col-lg-2 control-label'))) ?>
        <div class="col-sm-9 col-lg-10">
            <?php echo $this->formText($form->get('bank_type')->setAttribute('class','form-control')); ?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formlabel($form->get('bank_account_name')->setLabelAttributes(array('class' => 'col-sm-3 col-lg-2 control-label'))) ?>
        <div class="col-sm-9 col-lg-10">
            <?php echo $this->formText($form->get('bank_account_name')->setAttribute('class','form-control')); ?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formlabel($form->get('bank_account_card')->setLabelAttributes(array('class' => 'col-sm-3 col-lg-2 control-label'))) ?>
        <div class="col-sm-9 col-lg-10">
            <?php echo $this->formText($form->get('bank_account_card')->setAttribute('class','form-control')); ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9 col-lg-offset-2 col-lg-10">
        <?php echo $this->formSubmit($form->get('submit')->setAttributes(array(
            'class' => 'form-control btn btn-default'
        ))); ?>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
    
</div>