<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Cashier\Module'                        => __DIR__ . '/Module.php',
    'Cashier\Controller\IndexController' => __DIR__ . '/src/Cashier/Controller/IndexController.php',
    'CashierTest\Framework\TestCase'        => __DIR__ . '/tests/Cashier/Framework/TestCase.php',
    'CashierTest\SampleTest'                => __DIR__ . '/tests/Cashier/SampleTest.php',
);
