<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Merchant\Module'                        => __DIR__ . '/Module.php',
    'Merchant\Controller\IndexController' => __DIR__ . '/src/Merchant/Controller/IndexController.php',
    'MerchantTest\Framework\TestCase'        => __DIR__ . '/tests/Merchant/Framework/TestCase.php',
    'MerchantTest\SampleTest'                => __DIR__ . '/tests/Merchant/SampleTest.php',
);
