<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'EasypayInstall\Module'                        => __DIR__ . '/Module.php',
    'EasypayInstall\Controller\InstallController' => __DIR__ . '/src/EasypayInstall/Controller/InstallController.php',
    'EasypayInstallTest\Framework\TestCase'        => __DIR__ . '/tests/EasypayInstall/Framework/TestCase.php',
    'EasypayInstallTest\SampleTest'                => __DIR__ . '/tests/EasypayInstall/SampleTest.php',
);
