<?php echo $this->menu; ?>

<?php if (count($this->paginator)): ?>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'widget/pagination-control', array('route' => 'workbench/withdraw_paginator')); ?>

<ul>
<?php foreach ($this->paginator as $item): ?>
  <li>
    <div>编号:<?php echo $item['id']; ?></div>
    <div>商家id:<?php echo $item['merchant_id']; ?></div>
    <div>提现方式:<?php echo $item['withdraw_type']; ?></div>
    <div>提现交易号:<?php echo $item['withdraw_interface_trade_id']; ?></div>
    <div>金额:<?php echo $item['price']; ?></div>
    <div>申请时间:<?php echo $item['create_time']; ?></div>
    <div>处理时间:<?php echo $item['pay_time']; ?></div>
    <div>处理状态:<?php echo $item['pay_status']; ?></div>
    <div><a href="<?php echo $this->url('workbench/withdraw_edit',array('withdraw_id'=>$item['id'])); ?>">处理</a></div>
  </li>
<?php endforeach; ?>
</ul>


<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'widget/pagination-control', array('route' => 'workbench/withdraw_paginator')); ?>

<?php endif; ?>